CREATE TABLE POKEMON(
    ID_POKEMON INT,
    ID_ENTRENADOR INT,
    NUM_POKEDEX INT,
    MOTE VARCHAR(20),
    VITALIDAD INT NOT NULL,
    ATAQUE INT NOT NULL,
    ATA_ESPECIAL INT NOT NULL,
    DEFENSA INT NOT NULL,
    DEF_ESPECIAL INT NOT NULL,
    VELOCIDAD INT NOT NULL,
    NIVEL INT NOT NULL,
    FERTILIDAD INT NOT NULL CHECK (FERTILIDAD BETWEEN 0 AND 5),
    SEXO CHAR(1) NOT NULL CHECK (SEXO IN ('H','M','X')),
    ESTADO VARCHAR(20);
	EQUIPO INT NOT NULL DEFAULT 3,
	ID_OBJETO INT,
	CONSTRAINT POKEMON_PK PRIMARY KEY(ID_POKEMON)
);